[versions]
androidGradlePlugin = "8.5.2"
androidTools = "31.5.2"
androidxTracing = "1.3.0-alpha02"
androidxMacroBenchmark = "1.3.0"
androidDesugarJdkLibs = "2.0.4"
atomicfu = "0.25.0"
androidxAnnotation = "1.8.2"
androidxActivity = "1.9.1"
androidxCollection = "1.4.3"
androidxComposeBom = "2024.08.00"
androidxComposeRuntimeTracing = "1.0.0-beta01"
androidxComposeMaterial3Adaptive = "1.0.0-rc01"
androidxComposeMaterial3AdaptiveNavigationSuite = "1.3.0-rc01"
androidxCoreSplashscreen = "1.0.1"
androidxPaging = "3.3.2"
androidxDataStore = "1.1.1"
androidxLifecycle = "2.8.4"
androidxMedia3 = "1.4.0"
androidXMetrics = "1.0.0-beta01"
androidxProfileinstaller = "1.3.1"
androidxRoom = "2.7.0-alpha07"
androidxWork = "2.9.1"
androidxWindowManager = "1.3.0"
androidxTestCore = "1.6.1"
androidxTestExt = "1.2.1"
androidxTestRules = "1.6.1"
androidxTestRunner = "1.6.2"
androidxUiAutomator = "2.3.0"
androidxEspresso = "3.6.1"
banner = "2.2.3"
buildconfig = "5.4.0"
coil = "2.7.0"
coreKtx = "1.13.1"
composeSettings = "2.4.0"
composeCompilerReport = "1.4.0"
dfc = "1.0.8"
dokarSheets = "0.6.0-alpha05"
decompose = "3.1.0"
detekt = "1.23.6"
devappx = "2.4.6"
dependencyGuard = "0.5.0"
ffmpegKitFull = "6.0-2"
filekitCompose = "0.8.0"
hilt = "2.52"
hiltExt = "1.2.0"
jacoco = "0.8.12"
kotlin = "2.0.20"
kotlinDsl = "5.1.0"
kotlinxCoroutines = "1.8.1"
kotlinxSerialization = "1.7.1"
kotlinxCollections = "0.3.7"
kotlinxDatetime = "0.6.1"
ksp = "2.0.20-1.0.24"
ktor = "2.3.12"
lottie = "6.4.0"
monitor = "1.8.1"
mockk = "1.13.12"
moduleGraph = "2.6.0"
napier = "2.7.1"
nextlib = "0.8.2"
okhttp = "4.12.0"
okio = "3.9.0"
qrose = "1.0.1"
robolectric = "4.13"
roborazzi = "1.26.0"
sonner = "0.3.8"
sqllin = "1.3.2"
startupRuntime = "1.1.1"
striktCore = "0.35.1"
turbine = "1.1.0"
truth = "1.4.4"
urlencoderLib = "1.5.0"
[libraries]
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidxAnnotation" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivity" }
androidx-benchmark-macro = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidxMacroBenchmark" }
androidx-collection = { group = "androidx.collection", name = "collection", version.ref = "androidxCollection" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "androidxComposeMaterial3Adaptive" }
androidx-compose-material3-navigationSuite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "androidxComposeMaterial3AdaptiveNavigationSuite" }
androidx-compose-material3-adaptive-layout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version.ref = "androidxComposeMaterial3Adaptive" }
androidx-compose-material3-adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "androidxComposeMaterial3Adaptive" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-runtime-tracing = { group = "androidx.compose.runtime", name = "runtime-tracing", version.ref = "androidxComposeRuntimeTracing" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }

androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }

androidx-dataStore = { group = "androidx.datastore", name = "datastore", version.ref = "androidxDataStore" }
androidx-dataStore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "androidxDataStore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtimeTesting = { group = "androidx.lifecycle", name = "lifecycle-runtime-testing", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }

androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "androidxMedia3" }
androidx-media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "androidxMedia3" }
androidx-media3-common-ktx = { group = "androidx.media3", name = "media3-common-ktx", version.ref = "androidxMedia3" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "androidxMedia3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "androidxMedia3" }
androidx-media3-datasource-okhttp = { group = "androidx.media3", name = "media3-datasource-okhttp", version.ref = "androidxMedia3" }
androidx-metrics = { group = "androidx.metrics", name = "metrics-performance", version.ref = "androidXMetrics" }

androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "androidxPaging" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidxPaging" }
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "androidxPaging" }

androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "androidxProfileinstaller" }

androidx-startup-runtime = { group = "androidx.startup", name = "startup-runtime", version.ref = "startupRuntime" }

androidx-tracing-ktx = { group = "androidx.tracing", name = "tracing-ktx", version.ref = "androidxTracing" }
androidx-test-core = { group = "androidx.test", name = "core-ktx", version.ref = "androidxTestCore" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidxUiAutomator" }

androidx-window-core = { group = "androidx.window", name = "window-core", version.ref = "androidxWindowManager" }

androidx-work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "androidxWork" }
androidx-work-testing = { group = "androidx.work", name = "work-testing", version.ref = "androidxWork" }

banner = { group = "io.github.youth5201314", name = "banner", version.ref = "banner" }

compose-settings = { module = "com.github.alorma.compose-settings:ui-tiles", version.ref = "composeSettings" }

coil-kt = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coil" }
coil-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }
coil-video = { group = "io.coil-kt", name = "coil-video", version.ref = "coil" }

decompose = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
decompose-compose = { group = "com.arkivanov.decompose", name = "extensions-compose", version.ref = "decompose" }

dfc = { module = "com.lazygeniouz:dfc", version.ref = "dfc" }
dokar-sheets = { group = "io.github.dokar3", name = "sheets-m3", version.ref = "dokarSheets" }
dokar-sonner = { group = "io.github.dokar3", name = "sonner", version.ref = "sonner" }
devappx = { group = "io.github.afkt", name = "DevAppX", version.ref = "devappx" }

detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detekt-compose-rules = { group = "io.nlopez.compose.rules", name = "detekt", version = "0.4.10" }

ffmpeg-kit-full = { group = "com.arthenica", name = "ffmpeg-kit-full", version.ref = "ffmpegKitFull" }
filekit-compose = { module = "io.github.vinceglb:filekit-compose", version.ref = "filekitCompose" }
flexible-bottomsheet-material3 = { group = "com.github.skydoves", name = "flexible-bottomsheet-material3", version = "0.1.4" }

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
hilt-ext-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltExt" }

kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-serialization-protobuf = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf", version.ref = "kotlinxSerialization" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxCollections" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-atomicfu = { group = "org.jetbrains.kotlinx", name = "atomicfu", version.ref = "atomicfu" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }

lint-api = { group = "com.android.tools.lint", name = "lint-api", version.ref = "androidTools" }
lint-checks = { group = "com.android.tools.lint", name = "lint-checks", version.ref = "androidTools" }
lint-tests = { group = "com.android.tools.lint", name = "lint-tests", version.ref = "androidTools" }

molecule = { group = "app.cash.molecule", name = "molecule-runtime", version = "2.0.0" }

monitor = { group = "io.github.leavesczy", name = "monitor", version.ref = "monitor" }
monitor-no-op = { group = "io.github.leavesczy", name = "monitor-no-op", version.ref = "monitor" }

mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }

napier = { group = "io.github.aakira", name = "napier", version.ref = "napier" }

qrose = { module = "io.github.alexzhirkevich:qrose", version.ref = "qrose" }

robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }

sqllin-dsl = { group = "com.ctrip.kotlin", name = "sqllin-dsl", version.ref = "sqllin" }
sqllin-driver = { group = "com.ctrip.kotlin", name = "sqllin-driver", version.ref = "sqllin" }
sqllin-processor = { group = "com.ctrip.kotlin", name = "sqllin-processor", version.ref = "sqllin" }

strikt-core = { group = "io.strikt", name = "strikt-core", version.ref = "striktCore" }

truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

urlencoder-lib = { module = "net.thauvin.erik.urlencoder:urlencoder-lib", version.ref = "urlencoderLib" }

android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
compose-gradlePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-compiler-report-gradlePlugin = { group = "dev.shreyaspatil.compose-compiler-report-generator", name = "gradle-plugin", version.ref = "composeCompilerReport" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
kotlin-power-assert-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-power-assert", version.ref = "kotlin" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "androidxRoom" }
[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidxMacroBenchmark" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
compose-compiler-report-generator = { id = "dev.shreyaspatil.compose-compiler-report-generator", version.ref = "composeCompilerReport" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-power-assert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-dsl = { id = "org.gradle.kotlin.kotlin-dsl", version.ref = "kotlinDsl" }
module-graph = { id = "com.jraska.module.graph.assertion", version.ref = "moduleGraph" }
room = { id = "androidx.room", version.ref = "androidxRoom" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }

bilibilias-android-application = { id = "bilibilias.android.application", version = "unspecified" }
bilibilias-android-compose = { id = "bilibilias.android.compose", version = "unspecified" }
bilibilias-android-jacoco = { id = "bilibilias.android.jacoco", version = "unspecified" }
bilibilias-android-application-flavors = { id = "bilibilias.android.application.flavors", version = "unspecified" }
bilibilias-android-feature = { id = "bilibilias.android.feature", version = "unspecified" }
bilibilias-android-library = { id = "bilibilias.android.library", version = "unspecified" }
bilibilias-android-lint = { id = "bilibilias.android.lint", version = "unspecified" }
bilibilias-android-room = { id = "bilibilias.android.room", version = "unspecified" }
bilibilias-android-test = { id = "bilibilias.android.test", version = "unspecified" }
bilibilias-jvm-library = { id = "bilibilias.jvm.library", version = "unspecified" }
bilibilias-android-testoptions = { id = "bilibilias.android.testoptions", version = "unspecified" }
bilibilias-hilt = { id = "bilibilias.hilt", version = "unspecified" }
bilibilias-decompose = { id = "bilibilias.decompose", version = "unspecified" }
bilibilias-sqlLin = { id = "bilibilias.sqlLin", version = "unspecified" }
bilibilias-detekt = { id = "bilibilias.detekt", version = "unspecified" }
bilibilias-compose-compiler-report = { id = "bilibilias.compose.compiler.report", version = "unspecified" }

[bundles]
androidx-compose-ui-test = ["androidx-compose-ui-test", "androidx-compose-ui-testManifest", "androidx-test-espresso-core"]