[versions]
android = "8.6.1"
androidFilePicker = "1.0.1"
androidx-junit = "1.1.5"
appcenter = "5.0.4"
appcompat = "1.6.1"
asBottomDialog = "0.0.1beta10"
banner = "2.2.3"
brv = "1.5.8"
coil-compose = "2.6.0"
deeprecopy-compiler = "0.0.1-Beta-3"
constraintlayout = "2.1.4"
coreKtx = "1.12.0"
detekt = "1.23.5"
dfm = "0.9.25"
espresso-core = "3.5.1"
flexbox = "3.0.0"
github-GuidePro = "1.4.0"
glide = "4.16.0"
grpcProtobuf = "1.62.2"
grpcKotlinStub = "1.4.1"
hbmartinDetektRules = "0.1.4"
hilt = "2.51"
jiaozivideoplayer = "7.7.2.3300"
junit = "4.13.2"
jxl = "2.6.12"
kcomponent-compiler = "v1.0.8-rc7"
kotlin = "2.0.0"
kotlinx-coroutines-android = "1.8.0"
kotlinxSerializationCbor = "1.6.3"
ksp = "2.0.0-1.0.21"
ktor = "2.3.9"
lifecycle = "2.7.0"
lottie = "6.4.0"
material = "1.11.0"
mmkv = "1.3.3"
monitor = "1.6.0"
monitorNoOp = "1.4.6"
mtjSdkCircle = "4.0.7.6"
napier = "2.7.1"
okdownload = "1.0.7"
okhttp = "4.12.0"
okhttpBrotli = "4.12.0"
preferenceKtx = "1.2.1"
protobufJavaUtil = "3.25.2"
protobufKotlin = "3.25.3"
protobuf = "0.9.4"
room = "2.6.1"
rxFFmpeg = "4.9.0-lite"
ffmpegKit = "6.0-2"
srl-core = "1.7.2.4"
uiTimateBarX = "0.8.1"
work-runtime-ktx = "2.9.0"
xutils = "3.9.0"
activity-compose = "1.8.2"
compose-bom = "2024.05.00"
activity = "1.8.0"
[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
detekt-rules-libraries = { module = "io.gitlab.arturbosch.detekt:detekt-rules-libraries", version.ref = "detekt" }
detekt-rules-ruleauthors = { module = "io.gitlab.arturbosch.detekt:detekt-rules-ruleauthors", version.ref = "detekt" }
gitlab-detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpcProtobuf" }
grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpcKotlinStub" }
hbmartin-detekt-rules = { module = "com.github.hbmartin:hbmartin-detekt-rules", version.ref = "hbmartinDetektRules" }
kotlinx-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "kotlinxSerializationCbor" }
monitor = { module = "io.github.leavesczy:monitor", version.ref = "monitor" }
monitor-no-op = { module = "io.github.leavesczy:monitor-no-op", version.ref = "monitorNoOp" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-brotli = { module = "com.squareup.okhttp3:okhttp-brotli", version.ref = "okhttpBrotli" }
protobuf-java-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobufJavaUtil" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobufKotlin" }
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-runtime-ktx" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }

androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }

appcenter-crashes = { group = "com.microsoft.appcenter", name = "appcenter-crashes", version.ref = "appcenter" }
appcenter-analytics = { group = "com.microsoft.appcenter", name = "appcenter-analytics", version.ref = "appcenter" }
appcenter-distribute = { group = "com.microsoft.appcenter", name = "appcenter-distribute", version.ref = "appcenter" }

androidFilePicker = { group = "me.rosuh", name = "AndroidFilePicker", version.ref = "androidFilePicker" }

asBottomDialog = { group = "com.github.1250422131", name = "AsBottomDialog", version.ref = "asBottomDialog" }

banner = { group = "io.github.youth5201314", name = "banner", version.ref = "banner" }

brv = { group = "com.github.liangjingkanji", name = "BRV", version.ref = "brv" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose" }

deeprecopy-compiler = { group = "com.imcys.deeprecopy", name = "compiler", version.ref = "deeprecopy-compiler" }

deeprecopy-core = { group = "com.imcys.deeprecopy", name = "core", version.ref = "deeprecopy-compiler" }

dfm = { group = "com.github.ctiao", name = "dfm", version.ref = "dfm" }

flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

hyy920109-GuidePro = { group = "com.github.hyy920109", name = "GuidePro", version.ref = "github-GuidePro" }

jiaozivideoplayer = { group = "cn.jzvd", name = "jiaozivideoplayer", version.ref = "jiaozivideoplayer" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

jxl = { group = "net.sourceforge.jexcelapi", name = "jxl", version.ref = "jxl" }

kcomponent-compiler = { group = "com.github.xiaojinzi123.KComponent", name = "kcomponent-compiler", version.ref = "kcomponent-compiler" }
kcomponent-rx = { group = "com.github.xiaojinzi123.KComponent", name = "kcomponent-rx", version.ref = "kcomponent-compiler" }

kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }

ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

ktx = { group = "com.liulishuo.okdownload", name = "ktx", version.ref = "okdownload" }

lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }

mmkv = { group = "com.tencent", name = "mmkv", version.ref = "mmkv" }

mtj-sdk = { group = "com.baidu.mobstat", name = "mtj-sdk", version.ref = "mtjSdkCircle" }

okdownload = { group = "com.liulishuo.okdownload", name = "okdownload", version.ref = "okdownload" }

rxFFmpeg = { group = "com.github.microshow", name = "RxFFmpeg", version.ref = "rxFFmpeg" }
ffmpeg-kit-full = { group = "com.arthenica", name = "ffmpeg-kit-full", version.ref = "ffmpegKit" }

srl-core = { group = "com.github.dkzwm", name = "srl-core", version.ref = "srl-core" }
srl-ext-classics = { group = "com.github.dkzwm", name = "srl-ext-classics", version.ref = "srl-core" }
srl-ext-material = { group = "com.github.dkzwm", name = "srl-ext-material", version.ref = "srl-core" }

uiTimateBarX = { group = "com.gitee.zackratos", name = "UltimateBarX", version.ref = "uiTimateBarX" }

#xutils = { group = "org.xutils", name = "xutils", version.ref = "xutils" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
[plugins]
protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }